VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "AbstractDisplay"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'修飾文字列(開始枠)を出力する。
'''
Public Sub openMessage()

End Sub

'''
'メッセージ本体を出力する。
'''
Public Sub printMessage()

End Sub

'''
'修飾文字列(終了枠)を出力する。
'''
Public Sub closeMessage()

End Sub
