VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Product"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'文字列に飾り文字を付与して出力する。
'
'@param strValue 出力メッセージとして設定する文字列を指定する。
'''
Public Sub use(strValue As String)

End Sub

'''
'@return Product 自分自身のコピーを返す。
'''
Public Function createClone() As Product

End Function
