VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Factory"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'@param strOwner 製品の所有者の名前を指定する。
'@return Product 製品を生成して返す。
'''
Public Function createProduct(strOwner As String) As Product

End Function

'''
'製品を登録する。
'
'@param objProduct 登録対象とする製品を指定する。
'''
Public Sub registerProduct(objProduct As Product)

End Sub
