VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DisplayImpl"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'飾り枠(開始枠)を出力する。
'''
Public Sub rawOpen()

End Sub

'''
'メッセージ本体を出力する。
'''
Public Sub rawPrint()

End Sub

'''
'飾り枠(終了枠)を出力する。
'''
Public Sub rawClose()

End Sub
