VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Builder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'@param title タイトルとして出力する文字列を指定する。
'''
Public Sub makeTitle(title As String)

End Sub

'''
'@param str 小見出しとして出力する文字列を指定する。
'''
Public Sub makeString(str As String)

End Sub

'''
'@param items リストとして出力する文字列を格納した配列を指定する。
'''
Public Sub makeItems(items As Variant)

End Sub

'''
'終了処理を実行する。
'''
Public Sub closeBuilder()

End Sub
